### ISSUE TITLE
only get [object Promise] as output

### ISSUE THREAD

**Issue by emlsh** [dunklesToast/IServ#5]
I'm working currently on a iServ desktop client and for the notification system i'd like to use your api for that. But i cant get it working. For example: if i use the `.getUnreadMails()` function i only get `[object Promise] ` as output.
Any idea?

**Comment by dunklesToast** [comment]
Hi!

The Library returns Promises. I guess you do not wait for them to resolve. You need to use it like this:

```
const IServ = require('../index');
const iserv = new IServ(process.env.host, process.env.username, process.env.password, false, false);

(async function f() {
    await iserv.login();
    const mails = await iserv.getUnreadMails();
    console.log(mails)
})();
```

Or, if you need to use `.then()`

```
const IServ = require('../index');
const iserv = new IServ(process.env.host, process.env.username, process.env.password, false, false);

function f() {
    iserv.login().then(() => {
         iserv.getUnreadMails().then((mails) => {
            console.log(mails) 
        });
    });
});
```

**Comment by emlsh** [comment]
thank you but it doesnt work as well: 

`(node:11580) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (C:\Users\emmell\Documents\Projekte\Scripting\iserv-client-notify\node_modules\iserv\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\emmel\Documents\Projekte\Scripting\iserv-client-notify\node_modules\iserv\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\emmel\Documents\Projekte\Scripting\iserv-client-notify\node_modules\iserv\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

I don't understand why the request is failing: `Error: Request failed with status code 401`
I use that for instanciation: `const iserv = new IServ("*******.net", "*******", "******", false, false);`

**Comment by dunklesToast** [comment]
As stated in the module's README I have no IServ Account anymore and am unable to reproduce issues. It looks like IServ's Authentication Endpoint moved to `/iserv/app/login `. You could try to change the URL in the `node_modules/iserv/index.js` (Line 64) file and see if it works then. If so, please write me so I can update the Module.

**Comment by emlsh** [comment]
No still not working (same error message)

**Comment by michelhn** [comment]
Don't use `process.env.username` as this accesses your computer's name. Just give it another name and it should work.
