### ISSUE TITLE
IServ Exercises

### ISSUE THREAD

**Issue by michelhn** [dunklesToast/IServ#6]
I want to add a function that lets you fetch all the current exercises (Aufgaben) from IServ. However, I can't find anything about the API you used in the docs. Where did you find all the URLs? Did you just try it out?

**Comment by dunklesToast** [comment]
Hi Michel,

I used the Chrome DevTools to find all the needed URLs. You could try the same. If you'd like to add this functionality feel free to open a PR. If you need more help, let me know!

Btw: Does the login work for you? In #5 it seems like it's broken.

**Comment by michelhn** [comment]
I currently can't get it to work, IServ keeps throwing a 401 Unauthorized error for no reason. The credentials are correct and it works just fine in the browser, but somehow it doesn't work with your package. Any ideas?

**Comment by dunklesToast** [comment]
Well the Problem could be that IServ changed their "API". I have to IServ Account so I can't test it. If you could provide me your credentials I could take a look. Just send me a Mail me@dunklestoast.de.

**Comment by michelhn** [comment]
Nevermind, your example code doesn't work because process.env.username gets the computer's username and not the username from the .ENV file, resulting in me trying to log in with the wrong username all the time.

**Comment by dunklesToast** [comment]
Interesting. Never had this problem. But nice that it's working again 👍🏻

**Comment by michelhn** [comment]
> Hi Michel,
> 
> I used the Chrome DevTools to find all the needed URLs. You could try the same. If you'd like to add this functionality feel free to open a PR. If you need more help, let me know!
> 
> Btw: Does the login work for you? In #5 it seems like it's broken.

I just checked, works just fine for me. The exercise module doesn't make any requests to an internal API, seems like I'll have to scrape the stuff from there. Thanks for your help!

**Comment by dunklesToast** [comment]
Ah that sucks. But yea, some IServ Modules just do server side rendering :/
